# Parameters for compiling

ARDUINO_DIR     = /usr/share/arduino
TARGET          = output
ARDUINO_LIBS    =  


# Avrdude code for programming

BOARD_TAG               = uno
ARDUINO_PORT            = /dev/ttyACM1
AVRDUDE_ARD_PROGRAMMER  = arduino
AVRDUDE_ARD_BAUDRATE    = 115200
MONITOR_CMD             =
MONITOR_BAUDRATE        = 115200

# Arduino makefile

include $(ARDUINO_DIR)/Arduino.mk

